// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyo9S18Y0JaCMoLWd3k5unmKEdGCLnuSQ',
    appId: '1:251023284914:web:a4723dad35d0e405ec07ab',
    messagingSenderId: '251023284914',
    projectId: 'tgthon-de056',
    authDomain: 'tgthon-de056.firebaseapp.com',
    storageBucket: 'tgthon-de056.firebasestorage.app',
    measurementId: 'G-6V36REEWM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCmwNpZQ1T5XQ5Quy76dgQc-JDEn5e9vU',
    appId: '1:251023284914:android:895666bae67fe589ec07ab',
    messagingSenderId: '251023284914',
    projectId: 'tgthon-de056',
    storageBucket: 'tgthon-de056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIrer4qurwU0OfI9vEIhPs36qVWOoBa2E',
    appId: '1:251023284914:ios:79144c3a384647dbec07ab',
    messagingSenderId: '251023284914',
    projectId: 'tgthon-de056',
    storageBucket: 'tgthon-de056.firebasestorage.app',
    iosBundleId: 'com.example.flutterWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIrer4qurwU0OfI9vEIhPs36qVWOoBa2E',
    appId: '1:251023284914:ios:79144c3a384647dbec07ab',
    messagingSenderId: '251023284914',
    projectId: 'tgthon-de056',
    storageBucket: 'tgthon-de056.firebasestorage.app',
    iosBundleId: 'com.example.flutterWork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyo9S18Y0JaCMoLWd3k5unmKEdGCLnuSQ',
    appId: '1:251023284914:web:8a5e09e2b25132a8ec07ab',
    messagingSenderId: '251023284914',
    projectId: 'tgthon-de056',
    authDomain: 'tgthon-de056.firebaseapp.com',
    storageBucket: 'tgthon-de056.firebasestorage.app',
    measurementId: 'G-SMZDHJDBGP',
  );
}
